# Multi-stage build for optimized production image

FROM node:21.7-alpine AS base

# Install dependencies only when needed
FROM base AS deps

# https://github.com/nodejs/docker-node/tree/main/#nodealpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the available lockfile
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --frozen-lockfile; \
  else echo "No lockfile found, falling back to npm install" && npm install; \
  fi

# Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Example build-time args (add/remove as needed)
ARG NEXT_PUBLIC_BACKEND_API_URL
# Add more ARG instructions here if your build relies on them

# Expose args to the build environment
ENV NEXT_PUBLIC_BACKEND_API_URL=$NEXT_PUBLIC_BACKEND_API_URL

# Disable telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

RUN \
  if [ -f yarn.lock ]; then yarn build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
  else echo "Using npm run build" && npm run build; \
  fi

# Production image
FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Prepare directory for Next.js cache/output
RUN mkdir .next && chown nextjs:nodejs .next

# Copy the standalone production build
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by `next build` with output: "standalone"
CMD ["node", "server.js"]

